// Analog 14 = PC4
#define ANALOG_14 EFI_ADC_14

// IAT = Analog Temp 2 = PC5
#define PROTEUS_IN_ANALOG_TEMP_2 EFI_ADC_15
#define PROTEUS_IN_IAT PROTEUS_IN_ANALOG_TEMP_2

// CLT = Analog Temp 3 = PB0
#define PROTEUS_IN_ANALOG_TEMP_3 EFI_ADC_8
#define PROTEUS_IN_CLT PROTEUS_IN_ANALOG_TEMP_3

// Analog Temp 4 = PB1
#define PROTEUS_IN_ANALOG_TEMP_4 EFI_ADC_9

// MAP = Analog volt 1 = PC0
#define TPS1_IN EFI_ADC_10
#define PROTEUS_IN_MAP PROTEUS_IN_ANALOG_VOLT_1

// TPS = Analog volt 2 = PC1
#define PROTEUS_IN_ANALOG_VOLT_2 EFI_ADC_11
#define PROTEUS_IN_TPS PROTEUS_IN_ANALOG_VOLT_2

// PC2
#define PROTEUS_IN_ANALOG_VOLT_3 EFI_ADC_12
#define PROTEUS_IN_TPS1_2 PROTEUS_IN_ANALOG_VOLT_3

// PC3
#define PROTEUS_IN_ANALOG_VOLT_4 EFI_ADC_13
#define PROTEUS_IN_TPS2_1 PROTEUS_IN_ANALOG_VOLT_4

// PA0
#define IAT_IN EFI_ADC_0

// PA1
#define PROTEUS_IN_ANALOG_VOLT_6 EFI_ADC_1
#define PROTEUS_IN_AV_6_DIGITAL Gpio::A1

// PA2
#define PROTEUS_IN_ANALOG_VOLT_7 EFI_ADC_2
#define PROTEUS_IN_PPS2 PROTEUS_IN_ANALOG_VOLT_7

// PA3
#define MAP_IN EFI_ADC_3
#define PROTEUS_IN_AV_8_DIGITAL Gpio::A3

// PA4
#define CLT_IN EFI_ADC_4
#define PROTEUS_IN_PPS PROTEUS_IN_ANALOG_VOLT_9

// PA5
#define PROTEUS_IN_ANALOG_VOLT_10 EFI_ADC_5
#define PROTEUS_IN_AV_10_DIGITAL Gpio::A5

// PA6
#define BATT_V EFI_ADC_6
#define PROTEUS_IN_AV_11_DIGITAL Gpio::A6
