// DO NOT EDIT MANUALLY, let automation work hard.

// auto-generated by PinoutLogic.java based on ../../../connectors/M100.yaml
#pragma once

Gpio GENERATED_OUTPUTS[] = {
	Gpio::E9, // INJ1
	Gpio::E11, // INJ2
	Gpio::E10, // INJ3
	Gpio::E12, // INJ4
	Gpio::E3, // Fuel Pump CTRL
	Gpio::E6, // Fan CTRL
	Gpio::B8, // TACH Out
	Gpio::E15, // Idle 2 CTRL
	Gpio::D7, // Idle 1 CTRL
	Gpio::D6, // Spare 1 Out
	Gpio::B7, // Spare 2 Out
	Gpio::E14, // Spare 3 Out
	Gpio::B3, // IGN1
	Gpio::B4, // IGN2
	Gpio::B5, // IGN3
	Gpio::B6, // IGN4
// "INJ1",
// "INJ2",
// "INJ3",
// "INJ4",
// "Fuel Pump CTRL",
// "Fan CTRL",
// "TACH Out",
// "Idle 2 CTRL",
// "Idle 1 CTRL",
// "Spare 1 Out",
// "Spare 2 Out",
// "Spare 3 Out",
// "IGN1",
// "IGN2",
// "IGN3",
// "IGN4",
}
