// DO NOT EDIT MANUALLY, let automation work hard.

// auto-generated by PinoutLogic.java based on ../../../connectors/M100.yaml
#include "pch.h"

// see comments at declaration in pin_repository.h
const char* getBoardSpecificPinName(brain_pin_e brainPin) {
	switch (brainPin) {
		case Gpio::B3:
			return "IGN1";
		case Gpio::B4:
			return "IGN2";
		case Gpio::B5:
			return "IGN3";
		case Gpio::B6:
			return "IGN4";
		case Gpio::B7:
			return "Spare 2 Out";
		case Gpio::B8:
			return "TACH Out";
		case Gpio::D4:
			return "ISO Digital IN1";
		case Gpio::D6:
			return "Spare 1 Out";
		case Gpio::D7:
			return "Idle 1 CTRL";
		case Gpio::D8:
			return "ISO Digital IN2";
		case Gpio::E0:
			return "HALL2-VR2";
		case Gpio::E1:
			return "HALL1-VR1";
		case Gpio::E10:
			return "INJ3";
		case Gpio::E11:
			return "INJ2";
		case Gpio::E12:
			return "INJ4";
		case Gpio::E14:
			return "Spare 3 Out";
		case Gpio::E15:
			return "Idle 2 CTRL";
		case Gpio::E2:
			return "HALL3-VR3";
		case Gpio::E3:
			return "Fuel Pump CTRL";
		case Gpio::E4:
			return "ISO Digital IN3";
		case Gpio::E6:
			return "Fan CTRL";
		case Gpio::E9:
			return "INJ1";
		default:
			return nullptr;
	}
	return nullptr;
}
